import type { RouteConfig } from '@viewfly/router'
import { ButtonPage } from './pages/ButtonPage'
import { DividerPage } from './pages/DividerPage'
import { InputPage } from './pages/InputPage'
import { InputNumberPage } from './pages/InputNumberPage'
import { DropdownPage } from './pages/DropdownPage'
import { MenuListPage } from './pages/MenuListPage'
import { TooltipPage } from './pages/TooltipPage'
import { PopoverPage } from './pages/PopoverPage'
import { SliderPage } from './pages/SliderPage'
import { SwitchPage } from './pages/SwitchPage'
import { CheckboxPage } from './pages/CheckboxPage'
import { RadioPage } from './pages/RadioPage'
import { SelectPage } from './pages/SelectPage'
import { ColorPickerPage } from './pages/ColorPickerPage'
import { SpacePage } from './pages/SpacePage'
import { TabsPage } from './pages/TabsPage'
import { IconsPage } from './pages/IconsPage'
import { HomePage } from './pages/HomePage'
import { NotFoundPage } from './pages/NotFoundPage'

export const routes: RouteConfig[] = [
  { path: '', component: HomePage },
  { path: 'button', component: ButtonPage },
  { path: 'divider', component: DividerPage },
  { path: 'input', component: InputPage },
  { path: 'input-number', component: InputNumberPage },
  { path: 'dropdown', component: DropdownPage },
  { path: 'menu-list', component: MenuListPage },
  { path: 'tooltip', component: TooltipPage },
  { path: 'popover', component: PopoverPage },
  { path: 'slider', component: SliderPage },
  { path: 'switch', component: SwitchPage },
  { path: 'checkbox', component: CheckboxPage },
  { path: 'radio', component: RadioPage },
  { path: 'select', component: SelectPage },
  { path: 'color-picker', component: ColorPickerPage },
  { path: 'space', component: SpacePage },
  { path: 'tabs', component: TabsPage },
  { path: 'icons', component: IconsPage },
  { path: '*', component: NotFoundPage },
]
