export { Tabs } from './Tabs'
export { TabList } from './TabList'
export { Tab } from './Tab'
export { TabPanel } from './TabPanel'
export type { TabsProps } from './Tabs'
export type { TabListProps } from './TabList'
export type { TabProps } from './Tab'
export type { TabPanelProps } from './TabPanel'
export type { VfuiTabsOrientation } from './context'
