/** 与 `assets/icons/style.css` 中 `.vf-icon-*` 一一对应 */
export const ICON_GLYPH_NAMES = [
  'enrich',
  'translation',
  'check',
  'summary',
  'simplify',
  'magic-wand',
  'ai',
  'continuation',
  'timeline',
  'step',
  'arrow-left',
  'arrow-right',
  'arrow-top',
  'arrow-bottom',
  'source-code',
  'insert-paragraph-after',
  'insert-paragraph-before',
  'plus',
  'table-border',
  'table-remove',
  'function',
  'paint-bucket',
  'background-color',
  'color',
  'hightlight-box',
  'table-edit',
  'table-split-columns',
  'align-middle',
  'align-bottom',
  'align-top',
  'palette',
  'split-cells',
  'merge-cells',
  'image',
  'music',
  'video',
  'unlink',
  'select',
  'tree',
  'more',
  'checkmark',
  'text-wrap',
  'heading-h1',
  'heading-h2',
  'heading-h3',
  'heading-h4',
  'heading-h5',
  'heading-h6',
  'heading',
  'copy',
  'paste',
  'history-back',
  'history-forward',
  'quotes-right',
  'bin',
  'list-numbered',
  'list',
  'link',
  'command',
  'shift',
  'ctrl',
  'opt',
  'checkbox-checked',
  'checkbox-unchecked',
  'cut',
  'line-height',
  'letter-spacing',
  'font-size',
  'bold',
  'underline',
  'italic',
  'strikethrough',
  'superscript',
  'subscript',
  'clear-formatting',
  'table',
  'pilcrow',
  'ltr',
  'rtl',
  'paragraph-left',
  'paragraph-center',
  'paragraph-right',
  'paragraph-justify',
  'indent-increase',
  'indent-decrease',
  'code',
  'flow-chart',
  'send',
  'message',
] as const

export type IconGlyphName = (typeof ICON_GLYPH_NAMES)[number]

/** 便于遍历；值为占位，请勿依赖字段含义 */
export const ICON_PATHS = Object.freeze(
  Object.fromEntries(ICON_GLYPH_NAMES.map((name) => [name, true as const])),
) as Readonly<Record<IconGlyphName, true>>
